### PR TITLE
use parking_lot

### PR DESCRIPTION
**Pull request by cssivision**

### CODE REVIEW

**Comment by stjepang** [comment]
Are there any significant improvements in benchmarks? I feel hesitant about adding a new dependency if not.

**Comment by raftario** [comment]
Could this be made into an optional feature while defaulting to the standard library ?

**Comment by raftario** [comment]
As of performance improvements, the main one is that `parking_lot::Condvar` is a lot cheaper to create compared to `std::sync::Condvar` cause the latter allocates.

**Comment by taiki-e** [comment]
I'm okay with adding this as an optional feature, but I'd like to know how much this actually improves performance before merging. (I know parking_lot is basically faster than std, but switching to it doesn't necessarily help improve overall performance.)

**Comment by taiki-e** [comment]
Closing -- std mutex enough fast since https://github.com/rust-lang/rust/pull/95035

**Pull request closed without merging**
